### ISSUE TITLE
Array and index

### ISSUE THREAD

**Issue by edmondklai** [blueakashi/practice#6]
You have an array of names ["John", "Paul", "George", "Ringo"]. Write a program that prints the name and its corresponding index in the array. For example, the output for the first element should be "0: John".

**Comment by blueakashi** [comment]
const names = ["John", "Paul", "George", "Ringo"]

for (let i = 0; i < names.length; i = i + 1) {
    console.log(i + ": " + names[i])
}

**Comment by edmondklai** [comment]
@blueakashi , can you commit your code to the repository instead of writing it in a comment? Thanks!
